"""Consolidate the P0 results into one document and choose the workshop six.

Two deliverables live here, and they share one rule: every number is read from
a built artefact in `bld/`, never restated from a report. If a table moves, the
document moves with it, and if a row the document needs is missing or
duplicated, `select_row` raises rather than letting a stale number through.

- `build_results_document` writes `docs/results.md`, the consolidated results
  text §22's Gate 2 asks for, extended to cover the simulation. It is organised
  around the five Beiträge of §2, and every §19 main figure is read in the four
  parts §21 prescribes: what is measured, the central quantitative finding, why
  it matters for tax-transfer simulation, and what may not be concluded.
- `workshop_deck` picks the six figures §19 admits to the main talk out of the
  eight main figures, each with the one line that justifies its place.

Two §19 figures depend on modules still in flight. They stay in `MAIN_FIGURES`
with `FigureStatus.AWAITING_MODULE`, and the document carries a marked
placeholder section for them rather than prose about results that do not exist
yet.

The framing rules of §20 are enforced, not merely followed:
`forbidden_term_hits` fails the build on a banned term used as a claim, and
lets the same term through where the document is stating that the reading is
not permitted.
"""

import math
import re
import textwrap
from dataclasses import dataclass
from datetime import date
from enum import StrEnum
from types import MappingProxyType

import pandas as pd

from kdu.analysis.ba_validation import (
    RECOGNITION_COLUMN,
    recognition_rate_by_decile,
)
from kdu.analysis.proxy_error import PRIMARY_BENCHMARK
from kdu.config import ANALYSIS_DATE, BLD, ROOT, TABLES, WeightingScheme

# The consolidated results text (§22 Gate 2), regenerated by the pytask task.
RESULTS_DOCUMENT = ROOT / "docs" / "results.md"
# The workshop figure selection of §19, one row per main figure.
DECK_TABLE = TABLES / "workshop_figure_selection.csv"
# Column plain prose is wrapped at in the committed results document.
LINE_WIDTH = 88
# §19 admits at most this many figures to the main talk.
MAX_WORKSHOP_FIGURES = 6
# The needs measure, spelled out in full wherever it appears (§20).
NEEDS_MEASURE = "administrative Bruttokaltbedarf before income offsetting"
# Household size the two proxy-error maps are drawn for (§19 figures 1 and 2).
MAP_HOUSEHOLD_SIZES: tuple[int, int] = (1, 4)
# Model household carrying the headline exit-threshold number.
HEADLINE_HOUSEHOLD = "couple_children_8_14"
# Model household the budget curves are read for.
BUDGET_CURVE_HOUSEHOLD = "single_35"
# Terms §20 forbids, in the English of D13. A hit is a claim; the same word
# inside a sentence that denies it is what §21's fourth part is made of.
FORBIDDEN_TERMS: tuple[str, ...] = (
    "generosity",
    "generous",
    "restrictiveness",
    "restrictive",
    "causal effect",
    "actual KdU payment",
    "housing availability",
    "full Existenzminimum",
    "unknown Regelbedarfe",
)
# A Markdown list item: a dash, an asterisk or a number, then a space.
_LIST_ITEM_PATTERN = r"^\s*(?:[-*]|\d+\.)\s"
# Words that turn a forbidden term into a statement of what is not permitted.
_NEGATION_MARKERS: tuple[str, ...] = (
    "not",
    "never",
    "neither",
    "nor",
    "no ",
    "cannot",
    "forbid",
    "ban",
    "rather than",
    "without",
    "refuse",
)


# Paths of the artefacts `ResultsInputs` is assembled from, so the task and the
# tests agree on one list.
INPUT_PATHS = MappingProxyType(
    {
        "coverage": TABLES / "table1_coverage_and_quality.csv",
        "proxy_error_table": TABLES / "table2_proxy_error_by_household_size.csv",
        "proxy_error_frame": BLD / "proxy_error_gemeinde_household.parquet",
        "within_mietenstufe": TABLES / "table3_within_mietenstufe.csv",
        "dispersion": TABLES / "within_mietenstufe_dispersion.csv",
        "tilt": TABLES / "table_household_profile_tilt.csv",
        "rank_stability": TABLES / "table_household_profile_rank_stability.csv",
        "wogg_linked_check": TABLES / "table_household_profile_wogg_linked_check.csv",
        "microsim": TABLES / "table4_microsim.csv",
        "heating": TABLES / "table4_microsim_heating_sensitivity.csv",
        "rent_grid": TABLES / "table4_microsim_rent_grid.csv",
        "needs": TABLES / "table_needs_level.csv",
        "microsim_gemeinde": BLD / "microsim_gemeinde.parquet",
        "budget_curves": BLD / "microsim_budget_curves.parquet",
        "weighting_availability": TABLES / "proxy_error_weighting_availability.csv",
        "border_jumps_by_border_type": TABLES / "border_jump_by_border_type.csv",
        "border_jump_comparison_group": TABLES / "border_jump_comparison_group.csv",
        "ba_specifications": TABLES / "ba_validation_specifications.csv",
        "ba_regressor_variation": TABLES / "ba_validation_regressor_variation.csv",
        "ba_validation_frame": BLD / "ba_validation_jobcenter_household.parquet",
        "validation_worklist": BLD / "validation_worklist.csv",
        "manifest": BLD / "results_manifest.csv",
    },
)


class FigureStatus(StrEnum):
    """Whether a §19 main figure exists in `bld/figures` yet."""

    BUILT = "built"
    """The producing module has run and the figure is on disk."""
    AWAITING_MODULE = "awaiting_module"
    """The producing module is still in flight; the document says so."""


@dataclass(frozen=True)
class MainFigure:
    """One of the eight §19 main figures and its workshop-deck verdict."""

    number: int
    """Position in the §19 list, 1 to 8."""
    title: str
    """Short title, as the figure is referred to in the talk."""
    filename: str
    """File in `bld/figures`, or the name the pending module will write."""
    beitrag: int
    """Which of the five §2 Beiträge the figure carries."""
    status: FigureStatus
    """Whether the figure is built or still awaited."""
    in_deck: bool
    """Whether it is one of the at most six figures of the main talk (§19)."""
    reason: str
    """One line: why it is in the deck, or where it goes instead."""
    module: str
    """The producing analysis module, for example `"P0.3"`."""


MAIN_FIGURES: tuple[MainFigure, ...] = (
    MainFigure(
        number=1,
        title="Map of the log proxy error, household size 1",
        filename="fig_proxy_error_log_map_h1.html",
        beitrag=1,
        status=FigureStatus.BUILT,
        in_deck=True,
        reason=(
            "Beitrag 1 in one picture: the substitution error is spatially "
            "structured, so it cannot be absorbed into a national constant."
        ),
        module="P0.3",
    ),
    MainFigure(
        number=2,
        title="Map of the log proxy error, household size 4",
        filename="fig_proxy_error_log_map_h4.html",
        beitrag=1,
        status=FigureStatus.BUILT,
        in_deck=True,
        reason=(
            "Shown beside figure 1 on the shared colour scale; the pair, not "
            "either map alone, is what shows the error moves with household "
            "size."
        ),
        module="P0.3",
    ),
    MainFigure(
        number=3,
        title="Boxplots of K/W within the Wohngeld-Mietenstufen",
        filename="fig_within_mietenstufe_ratio.html",
        beitrag=3,
        status=FigureStatus.BUILT,
        in_deck=True,
        reason=(
            "Beitrag 3, and the figure that speaks directly to model builders: "
            "it shows what the Mietenstufe, the only regional housing "
            "parameter such models carry, leaves unexplained."
        ),
        module="P0.4",
    ),
    MainFigure(
        number=4,
        title="Familien-Tilt against the average relative KdU level",
        filename="fig_household_profile_tilt_scatter.html",
        beitrag=2,
        status=FigureStatus.BUILT,
        in_deck=True,
        reason=(
            "Beitrag 2: the error changes with household size inside one and "
            "the same Gemeinde, so no fixed regional intercept can absorb it."
        ),
        module="P0.5",
    ),
    MainFigure(
        number=5,
        title="Distribution of the simulated exit-threshold shift",
        filename="fig_microsim_delta_exit_threshold.html",
        beitrag=4,
        status=FigureStatus.BUILT,
        in_deck=True,
        reason=(
            "The headline policy number: what the proxy error does to a "
            "simulated Transfer-Ausstiegsschwelle, in euro per month."
        ),
        module="P0.7",
    ),
    MainFigure(
        number=6,
        title="Budget curves for selected Gemeinden",
        filename="fig_microsim_budget_curves.html",
        beitrag=4,
        status=FigureStatus.BUILT,
        in_deck=True,
        reason=(
            "Makes the mechanism legible without a microsimulation "
            "background, and shows why the cap gap is an upper bound on the "
            "simulation error rather than the error itself."
        ),
        module="P0.7",
    ),
    MainFigure(
        number=7,
        title="BA validation: recognition rate by decile of K/W",
        filename="fig_ba_validation_recognition_by_decile.html",
        beitrag=1,
        status=FigureStatus.BUILT,
        in_deck=False,
        reason=(
            "Backup: the external validation answers a reviewer's question "
            "rather than carrying an argument of its own, and it may never be "
            "shown without the coefficient beside it, which a single slide "
            "makes hard (A20)."
        ),
        module="P1.2",
    ),
    MainFigure(
        number=8,
        title="Administrative border jumps",
        filename="fig_border_jumps_distribution.html",
        beitrag=3,
        status=FigureStatus.BUILT,
        in_deck=False,
        reason=(
            "Annex: the adjacency evidence of P1.1 is descriptive, with no "
            "identification strategy behind it (§20), so it documents the "
            "discontinuity rather than exploiting it."
        ),
        module="P1.1",
    ),
)


@dataclass(frozen=True)
class ResultsInputs:
    """Every built artefact the consolidated results text reads from."""

    coverage: pd.DataFrame
    """`table1_coverage_and_quality.csv`, one row per Bundesland."""
    proxy_error_table: pd.DataFrame
    """`table2_proxy_error_by_household_size.csv`."""
    proxy_error_frame: pd.DataFrame
    """`proxy_error_gemeinde_household.parquet`, for the sign shares."""
    within_mietenstufe: pd.DataFrame
    """`table3_within_mietenstufe.csv`."""
    dispersion: pd.DataFrame
    """`within_mietenstufe_dispersion.csv`."""
    tilt: pd.DataFrame
    """`table_household_profile_tilt.csv`."""
    rank_stability: pd.DataFrame
    """`table_household_profile_rank_stability.csv`."""
    wogg_linked_check: pd.DataFrame
    """`table_household_profile_wogg_linked_check.csv`."""
    microsim: pd.DataFrame
    """`table4_microsim.csv`."""
    heating: pd.DataFrame
    """`table4_microsim_heating_sensitivity.csv`."""
    rent_grid: pd.DataFrame
    """`table4_microsim_rent_grid.csv`."""
    needs: pd.DataFrame
    """`table_needs_level.csv`."""
    microsim_gemeinde: pd.DataFrame
    """`microsim_gemeinde.parquet`, for the budget-curve Gemeinden."""
    budget_curves: pd.DataFrame
    """`microsim_budget_curves.parquet`."""
    weighting_availability: pd.DataFrame
    """`proxy_error_weighting_availability.csv`."""
    border_jumps_by_border_type: pd.DataFrame
    """`border_jump_by_border_type.csv`, one row per linkage, `h` and border."""
    border_jump_comparison_group: pd.DataFrame
    """`border_jump_comparison_group.csv`, the §13.4 tight comparison group."""
    ba_specifications: pd.DataFrame
    """`ba_validation_specifications.csv`, one row per §14.4 regression."""
    ba_regressor_variation: pd.DataFrame
    """`ba_validation_regressor_variation.csv`, the D7 degeneracy check."""
    ba_validation_frame: pd.DataFrame
    """`ba_validation_jobcenter_household.parquet`, for the decile gradient."""
    validation_worklist: pd.DataFrame
    """`validation_worklist.csv`, for the automated agreement rate."""
    manifest: pd.DataFrame
    """`results_manifest.csv`, for the reproduction section."""


def workshop_deck(
    figures: tuple[MainFigure, ...] = MAIN_FIGURES,
) -> tuple[MainFigure, ...]:
    """Return the figures admitted to the main talk (§19).

    Args:
        figures: The §19 main-figure programme.

    Returns:
        The selected figures in §19 order.

    Raises:
        ValueError: If more than `MAX_WORKSHOP_FIGURES` are selected, or if a
            selected figure is not built.

    """
    selected = tuple(figure for figure in figures if figure.in_deck)
    if len(selected) > MAX_WORKSHOP_FIGURES:
        msg = (
            f"§19 admits at most {MAX_WORKSHOP_FIGURES} figures to the main "
            f"talk; {len(selected)} are selected"
        )
        raise ValueError(msg)
    pending = [
        figure.filename
        for figure in selected
        if figure.status is not FigureStatus.BUILT
    ]
    if pending:
        msg = f"a figure in the deck is not built yet: {', '.join(pending)}"
        raise ValueError(msg)
    return selected


def build_deck_table(
    figures: tuple[MainFigure, ...] = MAIN_FIGURES,
) -> pd.DataFrame:
    """Tabulate the §19 figure programme and the workshop selection.

    Args:
        figures: The §19 main-figure programme.

    Returns:
        One row per main figure with its number, title, file, Beitrag,
        producing module, build status, deck membership and the one-line
        justification.

    """
    return pd.DataFrame(
        [
            {
                "figure_number": figure.number,
                "title": figure.title,
                "filename": figure.filename,
                "beitrag": figure.beitrag,
                "analysis_module": figure.module,
                "status": str(figure.status),
                "in_workshop_deck": figure.in_deck,
                "reason": figure.reason,
            }
            for figure in figures
        ],
    ).sort_values("figure_number", kind="stable")


def select_row(frame: pd.DataFrame, **filters: object) -> pd.Series:
    """Return the single row matching `filters`, raising if it is not unique.

    Every number in the results document comes through here, so a table that
    gains, loses or renames a row breaks the build instead of silently
    changing what the document claims.

    Args:
        frame: The table to select from.
        **filters: Column-value pairs that must all hold.

    Returns:
        The matching row.

    Raises:
        ValueError: If no row or more than one row matches.

    """
    mask = pd.Series(data=True, index=frame.index)
    for column, value in filters.items():
        mask &= frame[column] == value
    matched = frame.loc[mask]
    if len(matched) != 1:
        msg = (
            f"expected exactly one row for {filters}, found {len(matched)}; "
            f"the artefact this number is read from has changed shape"
        )
        raise ValueError(msg)
    return matched.iloc[0]


def forbidden_term_hits(text: str) -> tuple[str, ...]:
    """Return the §20 terms `text` uses as a claim rather than as a denial.

    A sentence that says a reading is not permitted must be able to name the
    reading; a sentence that asserts it may not. The two are separated by
    looking for a negation marker in the sentence carrying the term.

    Args:
        text: The document to check.

    Returns:
        Every offending sentence-and-term pair, as `"term: sentence"`.

    """
    hits = []
    for sentence in re.split(r"(?<=[.!?])\s+|\n", text):
        lowered = sentence.lower()
        if any(marker in lowered for marker in _NEGATION_MARKERS):
            continue
        hits.extend(
            f"{term}: {sentence.strip()}" for term in FORBIDDEN_TERMS if term in lowered
        )
    return tuple(hits)


def wrap_markdown(text: str, width: int = LINE_WIDTH) -> str:
    """Re-wrap prose to `width`, leaving headings, lists and code fences alone.

    Numbers are interpolated into prose written at a fixed width, which leaves
    the raw text ragged; wrapping afterwards is what keeps the committed
    document readable as a diff.

    Args:
        text: The assembled Markdown.
        width: Column to wrap plain paragraphs at.

    Returns:
        The document with every plain paragraph re-wrapped and a trailing
        newline.

    """
    blocks = []
    for block in text.split("\n\n"):
        stripped = block.strip()
        if not stripped:
            continue
        if stripped.startswith(("#", "```", "|")):
            blocks.append(stripped)
            continue
        if re.match(_LIST_ITEM_PATTERN, stripped):
            blocks.append(_wrap_list(stripped, width))
            continue
        blocks.append(
            textwrap.fill(" ".join(stripped.split()), width=width),
        )
    return "\n\n".join(blocks) + "\n"


def _wrap_list(block: str, width: int) -> str:
    items: list[str] = []
    for line in block.splitlines():
        if re.match(_LIST_ITEM_PATTERN, line):
            items.append(line.strip())
        elif items:
            items[-1] = f"{items[-1]} {line.strip()}"
        else:
            items.append(line.strip())
    return "\n".join(_wrap_list_item(item, width) for item in items)


def _wrap_list_item(item: str, width: int) -> str:
    """Wrap one list item, hanging its continuation lines under the text."""
    marker = re.match(_LIST_ITEM_PATTERN, item)
    indent = " " * len(marker[0]) if marker else ""
    return textwrap.fill(" ".join(item.split()), width=width, subsequent_indent=indent)


def build_results_document(
    inputs: ResultsInputs,
    figures: tuple[MainFigure, ...] = MAIN_FIGURES,
    analysis_date: date = ANALYSIS_DATE,
) -> str:
    """Assemble `docs/results.md` from the built artefacts.

    Args:
        inputs: The artefacts every number is read from.
        figures: The §19 main-figure programme.
        analysis_date: The Analysestichtag (D2), stated in the header.

    Returns:
        The document as Markdown.

    Raises:
        ValueError: If the assembled text uses a §20 term as a claim.

    """
    sections = (
        _header(inputs, analysis_date),
        _coverage_section(inputs),
        _beitrag_one(inputs, figures),
        _external_validation(inputs, figures),
        _beitrag_two(inputs, figures),
        _beitrag_three(inputs, figures),
        _border_jumps(inputs, figures),
        _beitrag_four(inputs, figures),
        _beitrag_five(inputs),
        _pending_section(figures),
        _deck_section(figures),
        _limitations_section(inputs),
        _definition_of_done(inputs, figures),
        _reproduction_section(inputs),
    )
    text = wrap_markdown("\n\n".join(section for section in sections if section))
    hits = forbidden_term_hits(text)
    if hits:
        joined = "\n  ".join(hits)
        msg = f"the results text uses §20 terms as claims:\n  {joined}"
        raise ValueError(msg)
    return text


def _header(inputs: ResultsInputs, analysis_date: date) -> str:
    coverage = inputs.coverage
    gemeinden = int(coverage["n_gemeinden_main_sample"].sum())
    comparable = int(
        select_row(
            inputs.proxy_error_table,
            benchmark_variant=str(PRIMARY_BENCHMARK),
            weighting=str(WeightingScheme.GEMEINDE_UNWEIGHTED),
            household_size=1,
            group="all",
        )["n_gemeinden"],
    )
    regions = int(coverage["n_policy_regions_main_sample"].sum())
    return f"""# Results

Kommunale KdU-Obergrenzen as the missing regional parameter of German
tax-transfer models. This is the consolidated results text §22's Gate 2 asks
for, extended to cover the simulation of P0.6 and P0.7. It is organised around
the five Beiträge of §2, and every §19 main figure is read in the four parts
§21 prescribes.

Every number below is read from a built artefact in `bld/` by
`src/kdu/final/task_workshop_deck.py`. Nothing here is typed by hand, so the
document cannot drift away from the pytask build that produced it.

**What is measured.** `K` is the local maximum recognisable Bruttokaltmiete a
Kreis publishes under § 22 SGB II and § 35 SGB XII. `W` is the Höchstbetrag of
§ 12 WoGG for the Gemeinde's statutory Mietenstufe, in the Fassung in force
since 2025-01-01 (A1), **times the 10 % Sicherheitszuschlag** (D15). That
product, not the bare table, is the value a model without a local parameter
should substitute: such a model is by construction in the situation § 22 SGB II
case law addresses, and the fallback the BSG prescribes there is the WoGG table
plus the Zuschlag. Numbers against the bare table are reported throughout as the
`base` robustness variant. `D = K − W`, and
`L = 100 (log K − log W)`. Both are caps on what may be recognised, not amounts
anyone is paid. Where a need level is reported it is the {NEEDS_MEASURE},
which excludes heating.

**Sample.** {gemeinden:,} Gemeinden across {regions} Kreise, balanced over
household sizes 1 to 4, at the Analysestichtag {analysis_date.isoformat()}
(D2, D3). The `K − W` comparison runs on {comparable:,} of them, because
{gemeinden - comparable} are gemeindefreie Gebiete that the Anlage zur WoGV
does not list, so no Wohngeld benchmark exists for them under the statute
(A2). Both numbers appear wherever coverage is stated."""


def _coverage_section(inputs: ResultsInputs) -> str:
    coverage = inputs.coverage
    total = int(coverage["n_gemeinden_total"].sum())
    main = int(coverage["n_gemeinden_main_sample"].sum())
    population_share = (
        100.0
        * coverage["population_main_sample"].sum()
        / coverage["population_total"].sum()
    )
    weighted_a = _weighted_tier_share(coverage, "share_quality_a")
    weighted_c = _weighted_tier_share(coverage, "share_quality_c")
    published = _weighted_tier_share(coverage, "share_published_gross_cold")
    highest = coverage.sort_values("share_gemeinden_main_sample").iloc[-1]
    lowest = coverage.sort_values("share_gemeinden_main_sample").iloc[0]
    passing = int((inputs.validation_worklist["auto_check_result"] == "pass").sum())
    checked = _checked_count(inputs.validation_worklist)
    rate = _agreement_rate(inputs.validation_worklist)
    worklist = len(inputs.validation_worklist)
    return f"""## Coverage, and where the evidence stops

The main sample covers {main:,} of {total:,} Gemeinden and
{population_share:.1f} % of the population. Coverage by Bundesland is itself a
finding rather than noise: it runs from {lowest["share_gemeinden_main_sample"]:.1f} %
of Gemeinden in {lowest["bundesland"]} to
{highest["share_gemeinden_main_sample"]:.1f} % in {highest["bundesland"]}, and the
shortfall sits in Kreise that publish a Nettokaltmiete cap only or publish
nothing at all.

{weighted_a:.1f} % of main-sample Gemeinden are quality tier A and
{weighted_c:.1f} % are tier C; {published:.1f} % rest on a Bruttokaltmiete the
document prints outright rather than on one summed from published components.
Tier C Gemeinden are inside the main sample because D3 defines the sample by
completeness of the Bruttokaltmiete, not by tier, and every table can condition
on `quality_tier`.

§6.6's census of manual re-checks was waived on the data owner's judgement
(A9). What stands in its place is the automated validation that was possible
against the corpus text layer: {checked:,} observations checked, {passing:,}
passing, a {rate:.1f} % agreement rate on the checkable subset out of a
{worklist:,}-row worklist. That rate is the measured agreement on the subset a
text layer existed for, and it is not extrapolated to the rest of the table."""


def _beitrag_one(inputs: ResultsInputs, figures: tuple[MainFigure, ...]) -> str:
    parts = [
        """## Beitrag 1 — the Wohngeld-Höchstbetrag is not a precise proxy

**How to read the medians below.** Against the correct fallback of D15 the
median gap is close to zero at every household size. That is the point, not a
null result: it says the § 12 WoGG table plus the Sicherheitszuschlag is
approximately unbiased *on average over Germany*, and therefore that the whole
of the proxy error is dispersion. A level bias would be repairable with one
constant; dispersion is not, and it is what the per-Gemeinde quantiles, the
share of Gemeinden more than 100 € from the benchmark, and the mean absolute
gap measure. Against the bare table (`base`) the same medians sit roughly 10 %
higher, because that comparison charges the Sicherheitszuschlag to the local
Kreis as if it were an error.

Figures 1 and 2 of §19 are one object: two maps of `L` on a shared, zero-centred
colour scale, so the same colour means the same log gap at both household
sizes."""
    ]
    for size in MAP_HOUSEHOLD_SIZES:
        figure = _figure_by_number(figures, 1 if size == 1 else 2)
        parts.append(_map_interpretation(inputs, figure, size))
    return "\n\n".join(parts)


def _map_interpretation(
    inputs: ResultsInputs,
    figure: MainFigure,
    household_size: int,
) -> str:
    table = inputs.proxy_error_table
    unweighted = _proxy_row(table, household_size, "all", "gemeinde_unweighted")
    population = _proxy_row(table, household_size, "all", "gemeinde_population")
    exact = _proxy_row(
        table,
        household_size,
        "excluding_at_safety_markup",
        "gemeinde_unweighted",
    )
    union = _proxy_row(
        table,
        household_size,
        "excluding_wogg_linked",
        "gemeinde_unweighted",
    )
    bedarfsgemeinschaft = _proxy_row(
        table,
        household_size,
        "all",
        str(WeightingScheme.BEDARFSGEMEINSCHAFT),
    )
    shares = _sign_shares(inputs.proxy_error_frame, household_size)
    return f"""### Figure {figure.number} — {figure.title}

**What is measured.** For each of the {int(unweighted["n_gemeinden"]):,}
Gemeinden with both a local Bruttokaltmiete cap and a statutory Mietenstufe,
`L = 100 (log K − log W)` at household size {household_size}: the log gap
between the local cap and the value a tax-transfer model would substitute for
it.

**The central quantitative finding.** The unweighted median Gemeinde sits
{unweighted["median_eur"]:+,.0f} € above the Wohngeld benchmark, or
{unweighted["median_log"]:+.1f} log points; the population-weighted median is
{population["median_eur"]:+,.0f} € and the Bedarfsgemeinschaft-weighted median
{bedarfsgemeinschaft["median_eur"]:+,.0f} €. The spread is wide, from
{unweighted["p10_eur"]:+,.0f} € at the tenth percentile to
{unweighted["p90_eur"]:+,.0f} € at the ninetieth, and the sign is not uniform:
`D` is negative in {shares["negative"]:.1f} % of Gemeinden and exactly zero in
{shares["zero"]:.1f} %. The mean absolute gap is
{unweighted["mean_absolute_eur"]:,.0f} € per month, and it exceeds 100 € in
{unweighted["share_abs_gt_100"]:.1f} % of Gemeinden.

**The same finding with the WoGG-linked Gemeinden set aside.** Their gap is
zero by construction under D15, so every pooled figure above is a mixture of
them and the rest, and both readings are given side by side throughout.
Excluding the `exact_ratio` group ({int(exact["n_gemeinden"]):,} Gemeinden
remain, {unweighted["share_at_safety_markup_pct"]:.1f} % excluded) the median is
{exact["median_eur"]:+,.0f} €, the mean absolute gap
{exact["mean_absolute_eur"]:,.0f} € and the share beyond 100 €
{exact["share_abs_gt_100"]:.1f} %. Excluding the broader `linked_union` group
({int(union["n_gemeinden"]):,} remain, {unweighted["share_wogg_linked_flag_pct"]:.1f} %
excluded) the median is {union["median_eur"]:+,.0f} €, the mean absolute gap
{union["mean_absolute_eur"]:,.0f} € and the share beyond 100 €
{union["share_abs_gt_100"]:.1f} %. Setting the group aside raises the median
rather than lowering it, and raises the dispersion with it.

**Why it matters for tax-transfer simulation.** A model substituting `W` for
`K` does not make one nationwide error but a spatially structured one, running
in opposite directions in different regions. It therefore does not average out
across a national sample, and it cannot be absorbed into a constant or into a
Bundesland fixed effect.

**What may not be concluded.** A high cap is not evidence that a Kreis is more
generous and a low one is not evidence that it is more restrictive: the cap is
endogenous to the local housing market, to administrative procedure, and to how
a Kreis draws its Vergleichsräume. Nothing here identifies a causal effect of
any policy. Neither `K` nor `W` is an actual KdU payment; both are caps, and
what is recognised is the lesser of the cap and the actual Bruttokaltmiete.
Nothing here speaks to housing availability, which no cap can measure. In the
`exact_ratio` group the colour reports the definitional identity
`K = 1.10 × W` that BSG case law permits a Kreis without a schlüssiges Konzept
to adopt, and not an empirical regularity — which is why both the with and the
without reading are given above."""


def _beitrag_two(inputs: ResultsInputs, figures: tuple[MainFigure, ...]) -> str:
    figure = _figure_by_number(figures, 4)
    tilt_all = _tilt_row(inputs.tilt, "all")
    tilt_union = _tilt_row(inputs.tilt, "excluding_wogg_linked")
    tilt_bg = _tilt_row(
        inputs.tilt,
        "all",
        weighting=str(WeightingScheme.BEDARFSGEMEINSCHAFT),
    )
    spearman = select_row(
        inputs.rank_stability,
        statistic="spearman_proxy_error",
        household_size=4,
    )
    moving = select_row(
        inputs.rank_stability,
        statistic="share_moving_at_least_two_deciles_proxy_error",
        household_size=4,
    )
    check = select_row(inputs.wogg_linked_check, sample="main_h1_h4", tilt="tilt_h4")
    h1 = _proxy_row(inputs.proxy_error_table, 1, "all", "gemeinde_unweighted")
    h4 = _proxy_row(inputs.proxy_error_table, 4, "all", "gemeinde_unweighted")
    return f"""## Beitrag 2 — the deviation is household-specific

### Figure {figure.number} — {figure.title}

**What is measured.** The Familien-Tilt
`F = log(K4/W4) − log(K1/W1)` per Gemeinde, against the average of `log(K/W)`
over household sizes 1 to 4. `F` is positive where the local cap sits
relatively higher for a four-person household than for a single, and it is zero
by construction wherever `K` is a fixed multiple of `W` at both sizes.

**The central quantitative finding.** The unweighted median tilt is
{tilt_all["p50"]:+.4f} log points with a P10–P90 range of {tilt_all["p10"]:+.4f}
to {tilt_all["p90"]:+.4f}; {100 * tilt_all["share_exact_zero"]:.1f} % of
Gemeinden sit exactly at zero. Excluding the `linked_union` group the median is
{tilt_union["p50"]:+.4f} and the range widens to {tilt_union["p10"]:+.4f} to
{tilt_union["p90"]:+.4f}; weighting by Bedarfsgemeinschaften instead of counting
Gemeinden gives a median of {tilt_bg["p50"]:+.4f}. The same movement shows in
the euro gap itself, which runs from a median of {h1["median_eur"]:+,.0f} € at
household size 1 to {h4["median_eur"]:+,.0f} € at size 4, and in the ranking:
the Spearman correlation of the proxy error between the two sizes is
{spearman["value"]:.3f}, and {100 * moving["value"]:.1f} % of Gemeinden move at
least two deciles between them.

**Why it matters for tax-transfer simulation.** The mismeasurement is
correlated with household composition. A correction calibrated on
single-person households carries the wrong magnitude, and for a substantial
minority of Gemeinden the wrong sign, when the same model simulates a family.
No Gemeinde-level fixed effect can absorb an error that changes inside the
Gemeinde.

**What may not be concluded.** A steeply rising cap schedule is not evidence of
family-friendly local policy. A Kreis facing a market where large dwellings are
relatively expensive must set a steeper schedule to recognise the same housing
standard, so the tilt is endogenous to the local housing stock and to the
Vergleichsraum definition. The flagged group's tilt is
{100 * check["share_exactly_zero_flagged"]:.1f} % exactly zero and never exceeds
{check["max_abs_tilt_flagged"]:.4f} in absolute value; that residual is the
rounding of caps published in whole euro, and it is not a finding about those
Kreise."""


def _beitrag_three(inputs: ResultsInputs, figures: tuple[MainFigure, ...]) -> str:
    figure = _figure_by_number(figures, 3)
    h1 = select_row(inputs.within_mietenstufe, household_size=1, sample="all")
    h4 = select_row(inputs.within_mietenstufe, household_size=4, sample="all")
    h1_excl = select_row(
        inputs.within_mietenstufe,
        household_size=1,
        sample="excluding_wogg_linked",
    )
    dispersion = inputs.dispersion.query(
        "measure == 'kdu_bkc_cap' and stratum == 'all' and household_size == 1",
    )
    widest = dispersion.sort_values("p90_minus_p10").iloc[-1]
    typical = float(dispersion["p90_minus_p10"].median())
    above_fifty = 100 * float(
        (dispersion["share_abs_dev_above_50_eur"] * dispersion["n_gemeinden"]).sum()
        / dispersion["n_gemeinden"].sum(),
    )
    above_hundred = 100 * float(
        (dispersion["share_abs_dev_above_100_eur"] * dispersion["n_gemeinden"]).sum()
        / dispersion["n_gemeinden"].sum(),
    )
    return f"""## Beitrag 3 — the Mietenstufen compress substantial local heterogeneity

### Figure {figure.number} — {figure.title}

**What is measured.** The distribution of `K/W` within each of the seven
statutory Mietenstufen, one box per Mietenstufe and household size, over the
{int(h1["n_gemeinden"]):,} Gemeinden in {int(h1["n_policy_regions"])} Kreise that
carry both values. The companion table reports how much of the variation in
`log K` a Mietenstufe classification accounts for.

**The central quantitative finding.** A Mietenstufe classification accounts for
{100 * h1["r_squared"]:.1f} % of the variation in `log K` at household size 1
and {100 * h4["r_squared"]:.1f} % at size 4, leaving residual standard
deviations of {h1["residual_sd"]:.3f} and {h4["residual_sd"]:.3f} log points.
Inside a single Mietenstufe the typical P90 − P10 spread of the single-person
cap is {typical:,.0f} €, and it reaches {widest["p90_minus_p10"]:,.0f} € in
Mietenstufe {int(widest["mietenstufe"])}, which holds
{int(widest["n_gemeinden"]):,} Gemeinden. {above_fifty:.1f} % of Gemeinden sit
more than 50 € from the median of their own Mietenstufe and
{above_hundred:.1f} % more than 100 €. Excluding the `linked_union` group, whose
`K/W` is pinned beside 1.10 by construction, the explained share falls to
{100 * h1_excl["r_squared"]:.1f} % at household size 1 and the residual standard
deviation rises to {h1_excl["residual_sd"]:.3f}.

**Why it matters for tax-transfer simulation.** The Mietenstufe is the only
regional housing parameter such models currently carry. Assigning needs by
Mietenstufe therefore gives Gemeinden whose published caps differ by the amounts
above the same {NEEDS_MEASURE}, and the residual spread inside one Mietenstufe
is of the same order as the differences between adjacent Mietenstufen. Where
the residual is large, the simulated Bedarf, the simulated Anspruch and the
simulated exit threshold inherit the whole mismeasurement. For Gemeinden below
10,000 inhabitants the statutory rent level is determined Kreis-wide, which is
the institutional reason the compression is not evenly distributed.

**What may not be concluded.** Dispersion within a Mietenstufe is not evidence
that any Kreis is misapplying the law, and it is not a causal effect of the
Mietenstufe classification. The ratio of 1.10 in the flagged group follows from
BSG case law and is a definition, not a regularity. Nothing in the boxplots
speaks to housing availability: they compare two administrative parameters, not
markets."""


def _external_validation(inputs: ResultsInputs, figures: tuple[MainFigure, ...]) -> str:
    figure = _figure_by_number(figures, 7)
    spec = _ba_row(inputs.ba_specifications, "all", "log_cap_over_benchmark")
    without = _ba_row(
        inputs.ba_specifications,
        "excluding_linked_union",
        "log_cap_over_benchmark",
    )
    exact = _ba_row(
        inputs.ba_specifications,
        "exact_ratio_only",
        "log_cap_over_benchmark",
    )
    market = _ba_row(inputs.ba_specifications, "all", "log_market_over_cap")
    variation = select_row(
        inputs.ba_regressor_variation,
        linkage_group="all",
        validation_sample="main",
        regressor="log_cap_over_benchmark",
    )
    deciles = recognition_rate_by_decile(inputs.ba_validation_frame)
    low = deciles.iloc[0]
    high = deciles.iloc[-1]
    log_distance = math.log(
        float(high["cap_over_benchmark"]) / float(low["cap_over_benchmark"]),
    )
    observed_pp = 100.0 * float(
        high[RECOGNITION_COLUMN] - low[RECOGNITION_COLUMN],
    )
    implied_pp = 100.0 * abs(float(spec["estimate"])) * log_distance
    return f"""### Figure {figure.number} — {figure.title}

**What is measured.** Against the Statistik der Bundesagentur für Arbeit's
"Wohn- und Kostensituation" for the reference month, `R^BA` is the share of
actual Bruttokaltmiete a Jobcenter recognises and `N^BA = 1 − R^BA` the
non-recognised share. `N^BA` is regressed on `log(K/W)` and on
`log(M/K)`, with household-size and Bundesland fixed effects and standard
errors clustered on the Jobcenter, over {int(spec["n_obs"]):,} Jobcenter-by-
household-size rows in {int(spec["n_clusters"])} clusters.

**The central quantitative finding, and it is a conditional one.** A higher
local cap relative to the Wohngeld Höchstbetrag goes with a lower non-recognised
share: β on `log(K/W)` is {spec["estimate"]:+.4f} with a Jobcenter-clustered
standard error of {spec["cluster_se"]:.4f}, and {without["estimate"]:+.4f}
({without["cluster_se"]:.4f}) once the `linked_union` Jobcenter are dropped.
Greater market pressure relative to the cap goes the other way, β on `log(M/K)`
= {market["estimate"]:+.4f} ({market["cluster_se"]:.4f}). **The association is
conditional and not raw:** across deciles of `K/W` the mean ratio rises
{low["cap_over_benchmark"]:.3f} to {high["cap_over_benchmark"]:.3f}, a log
distance of {log_distance:.2f}, while the mean recognition rate moves only
{observed_pp:.2f} percentage points where the fitted β implies
{implied_pp:.2f}. The Bundesland fixed effects carry most of it, because Kreise
with high caps are disproportionately Kreise with expensive housing and the two
pull `N^BA` in opposite directions. The decile figure may never be shown without
the coefficient beside it (A20).

**Why it matters for tax-transfer simulation.** The sign is the one the design
predicts, on data collected by a different institution for a different purpose,
so the local cap the project measures is picking up something the
administrative record also sees. That is what an external validation is for: it
does not add precision to the proxy error, it tests whether `K` behaves like the
constraint it is claimed to be.

**What may not be concluded.** Nothing here is a causal effect: a Jobcenter's
recognition rate and its Kreis's cap are jointly determined by the same local
housing market. Within the `exact_ratio` group the regressor is degenerate —
`sd(log K/W)` is {variation["sd"]:.4f} overall against a clustered β of
{exact["estimate"]:+.4f} with a standard error of {exact["cluster_se"]:.4f} on
{int(exact["n_obs"])} rows — which is no evidence either way, exactly as D7
predicts. `M` is a Zensus Bestandsmiete measured net-cold against a gross-cold
cap, so `M/K` understates market pressure and speaks to no housing
availability. Neither `K` nor the recognised amount is an actual KdU payment."""


def _border_jumps(inputs: ResultsInputs, figures: tuple[MainFigure, ...]) -> str:
    figure = _figure_by_number(figures, 8)
    linkage = "excluding_linked_union"
    within = _jump_row(
        inputs.border_jumps_by_border_type, linkage, 4, "within_policy_region"
    )
    across = _jump_row(
        inputs.border_jumps_by_border_type, linkage, 4, "between_policy_regions"
    )
    states = _jump_row(
        inputs.border_jumps_by_border_type, linkage, 4, "between_bundeslaender"
    )
    across_h1 = _jump_row(
        inputs.border_jumps_by_border_type, linkage, 1, "between_policy_regions"
    )
    tight = select_row(
        inputs.border_jump_comparison_group,
        linkage=linkage,
        household_size=4,
    )
    across_pooled = _jump_row(
        inputs.border_jumps_by_border_type, "all", 4, "between_policy_regions"
    )
    tight_pooled = select_row(
        inputs.border_jump_comparison_group,
        linkage="all",
        household_size=4,
    )
    return f"""### Figure {figure.number} — {figure.title}

**What is measured.** Every pair of directly adjacent Gemeinden, matched on the
shared edges of the unsimplified boundary source, classified by whether the two
sit in one policy region, in two Kreise of one Bundesland, or in two
Bundesländer. `J` is the absolute euro difference between their caps. The
headline figures exclude the `linked_union` Gemeinden and the pairs flagged as
possible geometry artefacts; the pooled counterparts are given beside them.

**The central quantitative finding.** Inside a policy region the cap is flat:
{100 * within["share_zero_jump"]:.0f} % of the
{int(within["n_pairs"]):,} within-region pairs carry an identical four-person
cap and the median `J` is {within["p50_jump_eur"]:.0f} €. Across a Kreis
boundary the median four-person household faces a monthly step of
{across["p50_jump_eur"]:.0f} € over {int(across["n_pairs"]):,} pairs, and
{100 * across["share_above_100_eur"]:.1f} % of those pairs exceed 100 €. Across
a Bundesland boundary the median is {states["p50_jump_eur"]:.0f} € and
{100 * states["share_above_100_eur"]:.1f} % exceed 100 €, over
{int(states["n_pairs"]):,} pairs. The step grows with household size: at size 1
the same Kreis-boundary median is {across_h1["p50_jump_eur"]:.0f} €. The §13.4
tight comparison group — same Mietenstufe, Zensus rent within ten percent,
similar density, different policy region — retains
{int(tight["n_pairs"]):,} pairs and does **not** close the gap: median
{tight["p50_jump_eur"]:.0f} € with
{100 * tight["share_above_100_eur"]:.0f} % above 100 €.

**The same finding with the WoGG-linked Gemeinden left in.** Two linked Kreise
in one Mietenstufe carry identical caps by construction, so pooling adds pairs
that cannot jump. It barely moves the Kreis-boundary step, which is
{across_pooled["p50_jump_eur"]:.0f} € over {int(across_pooled["n_pairs"]):,}
pairs with {100 * across_pooled["share_above_100_eur"]:.1f} % beyond 100 €,
against {across["p50_jump_eur"]:.0f} € and
{100 * across["share_above_100_eur"]:.1f} % excluding them. It bites on the
§13.4 tight comparison group, where matching on Mietenstufe selects the linked
pairs disproportionately: {tight_pooled["p50_jump_eur"]:.0f} € over
{int(tight_pooled["n_pairs"]):,} pairs pooled, against
{tight["p50_jump_eur"]:.0f} € over {int(tight["n_pairs"]):,} excluding them.
The headline uses the excluding reading for that reason.

**Why it matters for tax-transfer simulation.** The cap is an administrative
step function on the map, constant inside a Kreis and discontinuous at its
edge, which is exactly the shape a Mietenstufe-based or a national parameter
cannot reproduce. Two Gemeinden that a model treats as one housing environment
can carry an {NEEDS_MEASURE} that differs by more than the median step one
additional person adds to the cap.

**What may not be concluded. This is an administrative discontinuity, never a
regression discontinuity.** Nothing here is a causal effect, and no design in
this project identifies one: households sort across these borders, Kreise are
not assigned their boundaries at random, and the tight comparison group narrows
the comparison without making it exogenous. The step is not evidence that
either side is applying the law wrongly, and a cap is not an actual KdU
payment."""


def _beitrag_four(inputs: ResultsInputs, figures: tuple[MainFigure, ...]) -> str:
    return "\n\n".join(
        (
            """## Beitrag 4 — the proxy error moves simulated claims and exit thresholds

The simulation runs GETTSIM 1.3 at Rechtsstand 2026 on the four §11.1
Modellhaushalte, twice per Gemeinde: once with the local cap and once with the
Wohngeld-Höchstbetrag. GETTSIM's own 10 €/m² warm housing rule is replaced
rather than reconfigured, because left in place it would have truncated both
scenarios to the same value and produced a false null (A6). All households are
declared beyond month 12, so the cap is in force.

As in Beitrag 1, the median shift is near zero because D15 benchmarks against
the fallback a correctly specified model would already apply. What moves the
simulation is the spread: the P10–P90 range of `Δy*` and the share of Gemeinden
whose exit threshold moves by more than 100 € in either direction. A model
substituting `W` is not wrong on average — it is wrong in a particular place,
and the sign of the error depends on which place.""",
            _exit_threshold_interpretation(inputs, _figure_by_number(figures, 5)),
            _budget_curve_interpretation(inputs, _figure_by_number(figures, 6)),
        ),
    )


def _exit_threshold_interpretation(
    inputs: ResultsInputs,
    figure: MainFigure,
) -> str:
    table = inputs.microsim
    headline = select_row(
        table,
        household_key=HEADLINE_HOUSEHOLD,
        sample="all Gemeinden",
    )
    headline_excl = select_row(
        table,
        household_key=HEADLINE_HOUSEHOLD,
        sample="excluding WoGG-linked Gemeinden",
    )
    single = select_row(table, household_key="single_35", sample="all Gemeinden")
    pensioner = select_row(
        table,
        household_key="pensioner_70",
        sample="all Gemeinden",
    )
    heating_low, heating_high = _heating_pair(inputs.heating, HEADLINE_HOUSEHOLD)
    heating_shift = abs(
        heating_high["delta_exit_threshold_median_m"]
        - heating_low["delta_exit_threshold_median_m"],
    )
    return f"""### Figure {figure.number} — {figure.title}

**What is measured.** `Δy* = y*^K − y*^W`, the shift in the gross monthly
income at which the simulated SGB II claim runs out, located by bisection to
one euro in each of {int(headline["n_cells"]):,} distinct simulation cells and
joined back to {int(headline["n_gemeinden"]):,} Gemeinden. The figure shows its
distribution for each Modellhaushalt.

**The central quantitative finding.** For {headline["household_label"]} the
median shift is {headline["delta_exit_threshold_median_m"]:+,.0f} € per month
(P10 {headline["delta_exit_threshold_p10_m"]:+,.0f} €, P90
{headline["delta_exit_threshold_p90_m"]:+,.0f} €), which is
{headline["delta_hours_median"]:.1f} weekly working hours at the 2026
Mindestlohn; it exceeds 100 € in absolute value in
{100 * headline["share_abs_delta_exit_over_100_eur"]:.1f} % of Gemeinden, and it
rises to {headline_excl["delta_exit_threshold_median_m"]:+,.0f} € once the
`linked_union` group is set aside. The single adult sees
{single["delta_exit_threshold_median_m"]:+,.0f} € and the pensioner
{pensioner["delta_exit_threshold_median_m"]:+,.0f} €. The population-weighted
median for the headline household is
{headline["delta_exit_threshold_population_weighted_median_m"]:+,.0f} €. The
claim difference at zero income is
{headline["delta_transfer_zero_median_m"]:+,.0f} € per month, and the maximum
claim difference is the same quantity measured a second time — they are one
outcome, not two independent pieces of evidence, because the Bedarf difference
is the constant `K − W` and both scenarios apply an identical Anrechnung
schedule (A16). Holding the cold cap fixed and moving heating costs from
{heating_low["heizkosten_m"]:,.0f} € to {heating_high["heizkosten_m"]:,.0f} €
leaves the claim difference unchanged at
{heating_low["delta_transfer_zero_median_m"]:+,.0f} € and moves the median exit
threshold by {heating_shift:,.0f} €;
that is a confirmation that the design isolates the cold cap, and it carries no
information beyond that.

**Why it matters for tax-transfer simulation.** The exit threshold is where
transfer withdrawal ends and the tax system takes over. A model substituting
`W` for `K` therefore misstates not only the level of the simulated claim but
the income range over which it is paid at all, and with it every participation
tax rate, caseload count and labour-supply margin computed from that range.

**What may not be concluded.** None of these Δ is a causal effect: they are the
difference between two ways of parameterising the same simulation, not the
consequence of any policy change. They are not a statement about what any
Bedarfsgemeinschaft receives, since `K` is a cap. Every Δ is conditional on the
cap being in force: inside the twelve-month Karenzzeit of § 22 Abs. 1 S. 2–3
SGB II actual Unterkunftskosten are recognised in full and the proxy error is
identically zero (D11). The Vorrangprüfung between SGB II, Wohngeld and
Kinderzuschlag assumes the wohngeldrechtlicher Teilhaushalt coincides with the
Bedarfsgemeinschaft, which bites hardest for the four-person household."""


def _budget_curve_interpretation(
    inputs: ResultsInputs,
    figure: MainFigure,
) -> str:
    shown = (
        inputs.budget_curves.loc[
            inputs.budget_curves["household_key"] == BUDGET_CURVE_HOUSEHOLD,
            ["ags", "quantile_label"],
        ]
        .drop_duplicates()
        .sort_values("quantile_label")
    )
    detail = shown.merge(
        inputs.microsim_gemeinde.loc[
            inputs.microsim_gemeinde["household_key"] == BUDGET_CURVE_HOUSEHOLD,
            ["ags", "gemeinde", "kdu_bkc_cap", "wogg_cap_m", "delta_exit_threshold_m"],
        ].drop_duplicates("ags"),
        on="ags",
        how="left",
    )
    label = str(
        select_row(
            inputs.microsim,
            household_key=BUDGET_CURVE_HOUSEHOLD,
            sample="all Gemeinden",
        )["household_label"],
    )
    listed = "; ".join(
        f"{row['quantile_label']} {row['gemeinde']} (K {row['kdu_bkc_cap']:,.0f} €, "
        f"W {row['wogg_cap_m']:,.0f} €, "
        f"Δy* {row['delta_exit_threshold_m']:+,.0f} €)"
        for _, row in detail.iterrows()
    )
    grid = inputs.rent_grid.loc[
        inputs.rent_grid["household_key"] == BUDGET_CURVE_HOUSEHOLD
    ]
    low = select_row(grid, rent_factor=0.5)
    mid = select_row(grid, rent_factor=0.9)
    binding = select_row(grid, rent_factor=1.0)
    return f"""### Figure {figure.number} — {figure.title}

**What is measured.** Disposable income against gross monthly earnings on a
25 € grid for {label}, drawn twice per Gemeinde — once under the local cap,
once under the Wohngeld-Höchstbetrag — for three Gemeinden at the P10, P50 and
P90 of the proxy-error distribution: {listed}.

**The central quantitative finding.** The two curves are a vertical shift of one
another over the whole range in which the claim is positive, and they meet at
the exit threshold, which they reach at different earnings. Whether the shift
exists at all depends on where the actual Bruttokaltmiete sits, which the §12.2
rent grid puts a number on: at 50 % of
`max(K, W)` the two scenarios are indistinguishable in
{100 * low["share_with_no_difference"]:.0f} % of cells, at 90 % in
{100 * mid["share_with_no_difference"]:.1f} %, and only once rent reaches
`max(K, W)` does the median claim difference reach its full
{binding["delta_transfer_zero_median_m"]:+,.0f} € with
{100 * binding["share_with_no_difference"]:.1f} % of cells still unaffected.

**Why it matters for tax-transfer simulation.** This is the figure that makes
the mechanism legible without a microsimulation background, and it is also the
one that keeps the headline honest: the cap gap is an upper bound on the
simulation error, not the error itself. A modeller can read straight off the
curves which households the substitution touches and which it leaves alone.

**What may not be concluded.** The headline rent assumption `m = max(K, W)` is
a construction that makes both caps bind, not an estimate of what anyone pays,
so the curves are not a description of any real household's budget. The rent
grid is normalised, not a rent distribution, so nothing here says how many
households sit at each point. The three Gemeinden are quantile illustrations
and are not representative of their Bundesländer."""


def _beitrag_five(inputs: ResultsInputs) -> str:
    needs = inputs.needs.query("breakdown == 'all'")
    unlinked = inputs.needs.query(
        "breakdown == 'wogg_linked_flag' and group == 'False'",
    )
    single = select_row(needs, household_key="single_35", breakdown="all")
    couple = select_row(needs, household_key=HEADLINE_HOUSEHOLD, breakdown="all")
    single_unlinked = select_row(unlinked, household_key="single_35")
    couple_unlinked = select_row(unlinked, household_key=HEADLINE_HOUSEHOLD)
    lowest_share = 100 * float(needs["kdu_share_median"].min())
    highest_share = 100 * float(needs["kdu_share_median"].max())
    return f"""## Beitrag 5 — the local KdU is part of a regionalised needs level

**What is measured.** The {NEEDS_MEASURE} of §11.2: the nationally uniform
Regelbedarfe and Mehrbedarfe of the Modellhaushalt plus the local
KdU-Obergrenze, before any income is offset. Regelbedarfsstufe 1 is 563 € for
2026 — a Nullrunde, confirmed against § 28a Abs. 5 SGB XII, since the
arithmetic Fortschreibung of 557 € is below the amount in force and may not
reduce it (A14).

**The central quantitative finding.** For {single["household_label"]} the
Regelbedarf is {single["regelbedarf_m"]:,.0f} € everywhere in Germany, and the
measure has a median of {single["need_kdu_median"]:,.0f} €, a P10–P90 span of
{single["need_kdu_p10"]:,.0f} € to {single["need_kdu_p90"]:,.0f} €, and a full
regional range of {single["need_kdu_range"]:,.0f} € across
{int(single["n_gemeinden"]):,} Gemeinden, of which
{int(single["n_gemeinden_with_benchmark"]):,} carry a Wohngeld benchmark to
compare against. The housing component is a median
{100 * single["kdu_share_median"]:.1f} % of it. For
{couple["household_label"]} the median is {couple["need_kdu_median"]:,.0f} €
with a regional range of {couple["need_kdu_range"]:,.0f} € and a housing share
of {100 * couple["kdu_share_median"]:.1f} %. Substituting the
Wohngeld-Höchstbetrag moves the measure by a median of
{single["need_difference_median"]:+,.0f} € and
{couple["need_difference_median"]:+,.0f} € respectively, pooled — and by
{single_unlinked["need_difference_median"]:+,.0f} € and
{couple_unlinked["need_difference_median"]:+,.0f} € with the WoGG-linked
Gemeinden set aside, where the difference is not zero by construction.

**Why it matters for tax-transfer simulation.** Most parameters of the German
minimum-income system are set federally, which invites the assumption that the
needs level is a national constant. It is not: between {lowest_share:.0f} % and
{highest_share:.0f} % of it is a regional administrative parameter, and a model
without that parameter has no way to reproduce the regional variation in
simulated need.

**What may not be concluded.** The measure excludes heating, so it is not a
complete subsistence level and may not be described as one. It is built on
caps, so it is the maximum a Bedarfsgemeinschaft's Bruttokaltmiete could be
recognised at, not an amount paid. The regional range is not a ranking of local
policy: it reflects housing markets, Vergleichsraum definitions and document
vintages at the same time. `fig_needs_level_distribution.html` carries this
Beitrag as a backup slide; §19 does not list it among the eight main figures."""


def _pending_section(figures: tuple[MainFigure, ...]) -> str:
    pending = [
        figure for figure in figures if figure.status is FigureStatus.AWAITING_MODULE
    ]
    if not pending:
        return ""
    rows = "\n".join(
        f"- **Figure {figure.number} — {figure.title}** ({figure.module}). "
        f"Placeholder: the producing module has not been built, so no number "
        f"is stated here. Expected file `bld/figures/{figure.filename}`."
        for figure in pending
    )
    return f"""## Placeholders — §19 figures whose modules are in flight

{rows}

Nothing in this section is a result. When the modules land, their figures enter
here with the same four-part reading, and the §19 programme is complete. The
external validation of P1.2 and the adjacency analysis of P1.1 are also the two
Definition-of-Done criteria this document reports as not yet met."""


def _deck_section(figures: tuple[MainFigure, ...]) -> str:
    deck = workshop_deck(figures)
    chosen = "\n".join(
        f"{position}. **{figure.title}** (`{figure.filename}`, Beitrag "
        f"{figure.beitrag}). {figure.reason}"
        for position, figure in enumerate(deck, start=1)
    )
    rest = "\n".join(
        f"- **{figure.title}** (`{figure.filename}`). {figure.reason}"
        for figure in figures
        if not figure.in_deck
    )
    return f"""## The workshop deck — six figures (§19)

§19 admits at most {MAX_WORKSHOP_FIGURES} figures to the main talk. The
selection is:

{chosen}

Everything else goes to backup or annex:

{rest}

Backup slides also carry the remaining built figures: the ECDF and the absolute
distribution of `D`, the Bundesland by household-size heatmap, the rent-point
figure of §8.4, the within-Mietenstufe cap boxplots and strata, the tilt map,
the tilt distribution, the decile transition matrix, the exit-threshold map,
the hours-equivalent figure, the proxy error against Δy*, and the needs-level
distribution. `bld/tables/workshop_figure_selection.csv` carries this table in
machine-readable form."""


def _limitations_section(inputs: ResultsInputs) -> str:
    coverage = inputs.coverage
    main = int(coverage["n_gemeinden_main_sample"].sum())
    without = int(coverage["n_without_wogg_benchmark"].sum())
    availability = select_row(
        inputs.weighting_availability,
        weighting=str(WeightingScheme.BEDARFSGEMEINSCHAFT),
    )
    agreement_rate = _agreement_rate(inputs.validation_worklist)
    return f"""## Limitations that travel with every number above

- **The Karenzzeit.** Under § 22 Abs. 1 S. 2–3 SGB II the cap is suspended for
  the first twelve months and actual Unterkunftskosten are recognised in full,
  so the proxy error is identically zero for a Bedarfsgemeinschaft inside it
  (D11). Every Δ reported here is conditional on the cap being in force. The
  BA product used for the external validation carries no Bezugsdauer, so the
  share of Bedarfsgemeinschaften inside the Karenzzeit is not scaled for.
- **{main - without:,} against {main:,}.** {without} main-sample Gemeinden have a
  local cap but no statutory Mietenstufe, so no Wohngeld benchmark exists for
  them at all and every `K − W` comparison runs on the smaller number (A2).
  §7's acceptance criterion of a complete Mietenstufe assignment is struck as
  unsatisfiable, with that reason recorded.
- **Two flagged groups, never one.** `exact_ratio` is the group with
  `K/W = 1.100` to five ten-thousandths, 12.9 % of Gemeinden at household size
  1, and it is the group for which the proxy error is a definitional identity.
  `linked_union` is the union of the notes-regex and ratio detectors, 18.8 %,
  and it is the right group when asking which Kreise lean on the § 12 WoGG
  table at all. Every with-and-without pair above states which of the two it
  uses; the two are not interchangeable (A12).
- **ΔT_max and ΔT(0) are one outcome.** They coincide in every cell by
  construction, and the heating sensitivity cannot move ΔT(0) at all. Neither
  may be presented as independent confirmation of the other (A16).
- **The manual validation census was waived** on the data owner's judgement
  (A9). The {agreement_rate:.1f} % automated agreement rate is measured on the
  subset with a text layer and is not extrapolated. 666 rows remain flagged
  `not_found_in_text` and 19 source citations resolve to no corpus file.
- **The Zensus cross-tabulation of floor area by rent is unavailable** without
  a registered account, so a market-stress indicator can compare only against
  the overall mean Gemeinde Nettokaltmiete. That ignores that small dwellings
  cost more per square metre and biases a single-person indicator in a known
  direction (A11). Nothing was substituted for it.
- **Document vintages are mixed**, from 2019 to 2026, and the sample carries
  every rule in force at the Stichtag (D2). `publication_date` is empty
  throughout the source register and `retrieval_date` is a file mtime, so both
  are proxies rather than records.
- **The Bedarfsgemeinschaft weighting rests on an assumption.**
  {availability["note"]}
- **Δy* is not computed across the rent grid.** Variante 2 delivers ΔT(0) at
  every rent factor but not the exit threshold, which would add a bisection at
  nine rent factors to every pytask build for a dimension whose shape is
  already clear (A17)."""


# The twelve §23 Definition-of-Done criteria, in the plan's order. Each carries
# the evidence the document points at; the verdict for the two that depend on a
# count is computed rather than written down.
DEFINITION_OF_DONE: tuple[tuple[str, str], ...] = (
    (
        "A cleaned Gemeinde-level KdU dataset for household sizes 1 to 5",
        "`kdu_municipality_household.parquet`, long and keyed "
        "`ags x household_size` over h = 1…5 (D14); the h = 1…4 balanced main "
        "sample and the separate h = 1…5 subsample are both built (D3).",
    ),
    (
        "An unambiguous policy-region assignment",
        "`policy_region_id = ags_kreis` for all 400 Kreise (D1). Within-Kreis "
        "dispersion is reported descriptively rather than flagged, because 210 "
        "Kreise define Vergleichsräume internally.",
    ),
    (
        "A temporally and conceptually matching Wohngeld benchmark",
        "`wogg_benchmark.parquet`, the § 12 WoGG Höchstbetrag times the BSG "
        "Sicherheitszuschlag, keyed on the statutory `wogv_mietstufe` (D15), "
        "cross-validated against three "
        "independent sources (A1, A7).",
    ),
    (
        "The complete distribution of the euro and log proxy error",
        "Table 2 and `proxy_error_gemeinde_household.parquet`, every household "
        "size under four weightings, three benchmark variants and both linkage "
        "groups.",
    ),
    (
        "Quantification of the heterogeneity inside the Mietenstufen",
        "Table 3 with the variance decomposition, the dispersion tables and "
        "the boxplot figure of Beitrag 3.",
    ),
    (
        "Analysis of the household-size profile",
        "The Familien-Tilt, the marginal amounts, the rank stability and the "
        "decile transition matrix of Beitrag 2.",
    ),
    (
        "A regionalised administrative needs level for the model households",
        "`table_needs_level.csv` and `needs_level_gemeinde.parquet` for all "
        "four §11.1 Modellhaushalte (Beitrag 5).",
    ),
    (
        "A standard-case claim and exit-threshold analysis",
        "Table 4, the budget curves and the exit-threshold distribution, "
        "located by bisection to one euro on GETTSIM, whose own "
        "housing cap was replaced rather than reconfigured (D10, A6).",
    ),
    (
        "At least one external validation",
        "The BA \u201cWohn- und Kostensituation\u201d validation above: "
        "`table5_external_validation.csv` and the §14.4 specifications, on "
        "data collected by a different institution for a different purpose.",
    ),
    (
        "A complete quality and methods appendix",
        "`quality_report.html`, `data_dictionary.csv`, `source_register.csv`, "
        "`exclusion_log.csv`, `validation_worklist.csv`, plus "
        "`docs/coverage_notes.md`, `docs/decision_log.md` and "
        "`docs/simulation_assumptions.md`.",
    ),
    (
        "Reproducible tables and figures",
        "",
    ),
    (
        "A clear separation of descriptive findings, simulations and causal claims",
        "Every figure carries the §21 four-part reading whose fourth part "
        "states what may not be concluded; `forbidden_term_hits` fails this "
        "build on a §20 term used as a claim; the border-jump evidence is "
        "labelled an administrative and never a regression discontinuity.",
    ),
)


def _definition_of_done(
    inputs: ResultsInputs,
    figures: tuple[MainFigure, ...],
) -> str:
    """Audit the twelve §23 criteria against what is actually on disk."""
    registered = len(inputs.manifest)
    outputs = _built_output_count()
    unregistered = _unregistered_outputs(inputs.manifest)
    built = sum(1 for figure in figures if figure.status is FigureStatus.BUILT)
    reproducible_verdict = "Met" if not unregistered else "Partially met"
    reproducible_evidence = (
        f"One pytask graph rebuilds every table and figure this document "
        f"reads, and all {built} §19 main figures are built. "
        f"`bld/results_manifest.csv` registers {registered} of the {outputs} "
        f"files under `bld/tables` and `bld/figures`, each with the seven §5.2 "
        f"fields."
    )
    if unregistered:
        reproducible_evidence += (
            f" {len(unregistered)} carry no manifest row and therefore no "
            f"recorded interpretation or limitation: "
            f"{', '.join(f'`{name}`' for name in unregistered)}."
        )
    rows = []
    for position, (criterion, evidence) in enumerate(DEFINITION_OF_DONE, start=1):
        verdict = reproducible_verdict if position == 11 else "Met"
        stated = reproducible_evidence if position == 11 else evidence
        rows.append(f"{position}. **{verdict} — {criterion}.** {stated}")
    listed = "\n".join(rows)
    headline = (
        "All twelve criteria are met."
        if not unregistered
        else f"Eleven of the twelve criteria are met; criterion 11 is "
        f"partially met, with {len(unregistered)} outputs unregistered."
    )
    return f"""## §23 Definition of Done — the audit

{headline} The two that were open at the last audit are the external
validation, which P1.2 closed, and the manifest coverage of the tables and
figures, which P1.1 and P1.2 closed by registering their own outputs.

{listed}

Met is not the same as finished. The waived validation census (A9), the
unavailable Zensus cross-tabulation (A11) and the Karenzzeit conditionality
(D11) are limitations of results that exist, not criteria left open."""


def _unregistered_outputs(manifest: pd.DataFrame) -> tuple[str, ...]:
    """Names of built tables and figures that carry no `results_manifest` row."""
    registered = (
        frozenset(manifest["filename"]) if "filename" in manifest else frozenset()
    )
    return tuple(sorted(_built_output_names() - registered))


def _built_output_names() -> frozenset[str]:
    """Every file under `bld/tables` and `bld/figures` a manifest row could name."""
    directories = (TABLES, BLD / "figures")
    return frozenset(
        path.name
        for directory in directories
        if directory.is_dir()
        for path in directory.iterdir()
        if path.is_file()
    )


def _built_output_count() -> int:
    """Count the files under `bld/tables` and `bld/figures` a manifest row could name."""
    return len(_built_output_names())


def _reproduction_section(inputs: ResultsInputs) -> str:
    manifest = inputs.manifest
    return f"""## Reproduction

```
pixi install
pixi run pytask      # rebuilds every artefact this document reads
pixi run pytest      # the test suite
```

`bld/results_manifest.csv` registers {len(manifest)} outputs, each with the
seven §5.2 fields: filename, analysis module, underlying dataset, script,
creation date, a one-line interpretation and its key limitation. That is every
file under `bld/tables/` and `bld/figures/`, the supporting robustness tables
included, so no output is presented without a recorded reading and caveat.

Language follows D13: English throughout, German kept only for terms with no
faithful translation."""


def _checked_count(worklist: pd.DataFrame) -> int:
    """Worklist rows the automatic amount check could settle either way."""
    outcomes = worklist["auto_check_result"]
    return int(outcomes.isin(["pass", "fail"]).sum())


def _agreement_rate(worklist: pd.DataFrame) -> float:
    """Percent of the checkable worklist whose amount is in its source text (A9)."""
    passing = int((worklist["auto_check_result"] == "pass").sum())
    return 100.0 * passing / _checked_count(worklist)


def _ba_row(specifications: pd.DataFrame, group: str, regressor: str) -> pd.Series:
    return select_row(
        specifications,
        linkage_group=group,
        validation_sample="main",
        household_sizes="1+2+3+4",
        regressor=regressor,
    )


def _jump_row(
    by_border_type: pd.DataFrame,
    linkage: str,
    household_size: int,
    border_type: str,
) -> pd.Series:
    return select_row(
        by_border_type,
        linkage=linkage,
        household_size=household_size,
        border_type=border_type,
    )


def _figure_by_number(figures: tuple[MainFigure, ...], number: int) -> MainFigure:
    for figure in figures:
        if figure.number == number:
            return figure
    msg = f"no §19 main figure numbered {number}"
    raise ValueError(msg)


def _proxy_row(
    table: pd.DataFrame,
    household_size: int,
    group: str,
    weighting: str,
) -> pd.Series:
    return select_row(
        table,
        benchmark_variant=str(PRIMARY_BENCHMARK),
        weighting=weighting,
        household_size=household_size,
        group=group,
    )


def _tilt_row(
    table: pd.DataFrame,
    group: str,
    weighting: str = str(WeightingScheme.GEMEINDE_UNWEIGHTED),
) -> pd.Series:
    return select_row(
        table,
        sample="main_h1_h4",
        tilt="tilt_h4",
        group=group,
        weighting_scheme=weighting,
    )


def _heating_pair(
    heating: pd.DataFrame,
    household_key: str,
) -> tuple[pd.Series, pd.Series]:
    rows = heating.loc[heating["household_key"] == household_key].sort_values(
        "heating_factor",
    )
    return rows.iloc[0], rows.iloc[-1]


def _sign_shares(frame: pd.DataFrame, household_size: int) -> dict[str, float]:
    cell = frame.loc[
        (frame["benchmark_variant"] == str(PRIMARY_BENCHMARK))
        & (frame["household_size"] == household_size)
        & frame["proxy_error_eur"].notna()
    ]
    error = cell["proxy_error_eur"].astype(float)
    return {
        "negative": 100.0 * float((error < 0).mean()),
        "positive": 100.0 * float((error > 0).mean()),
        "zero": 100.0 * float((error == 0).mean()),
    }


def _weighted_tier_share(coverage: pd.DataFrame, column: str) -> float:
    weights = coverage["n_gemeinden_main_sample"].astype(float)
    return float((coverage[column].astype(float) * weights).sum() / weights.sum())
